title: "Choi Wooseong Portfolio"
baseURL: "https://cws1513.github.io/"

defaultContentLanguage: ko
hasCJKLanguage: true

languages:
  ko:
    languageName: 한국어
    weight: 1
  en:
    languageName: English
    weight: 2

params:
  colorScheme: auto
  images: ["/images/profile.png"]
  seo:
    title: "Choi Wooseong Portfolio"
    description: "전북대학교 컴퓨터공학부 최우성의 포트폴리오 사이트"
    keywords: ["JBNU", "Portfolio", "Computer Science", "Choi Wooseong"]
