title: "Choi Wooseong Portfolio"
baseURL: "https://cws1513.github.io/"

defaultContentLanguage: ko
hasCJKLanguage: true
defaultContentLanguageInSubdir: false
removePathAccents: true

enableRobotsTXT: true
sitemap:
  _merge: deep

params:
  colorScheme: auto  # 다크/라이트 모드 자동
  images: ["/images/profile.png"]  # 대표 이미지
  seo:
    title: "Choi Wooseong Portfolio"
    description: "전북대학교 IT정보공학과 최우성의 포트폴리오"
    keywords: ["JBNU", "Portfolio", "IT Information Engineering", "Choi Wooseong"]
