
en:
  languageCode: en-us
  title: Choi Wooseong Portfolio
  params:
    description: A portfolio site for Choi Wooseong, Dept. of IT Information Engineering at JBNU.
  menu:
    main:
      - name: About
        url: '#about'
        weight: 10
      - name: Projects
        url: '#projects'
        weight: 20

ko:
  languageCode: ko-kr
  title: 최우성 포트폴리오
  params:
    description: 전북대학교 IT정보공학과 최우성의 포트폴리오 사이트
  menu:
    main:
      - name: 소개
        url: '#about'
        weight: 10
      - name: 프로젝트
        url: '#projects'
        weight: 20
