

main:
  - name: 홈
    url: '/'
    weight: 10
  - name: 소개
    url: '#about'
    weight: 20
  - name: 연락처
    url: '#contact'
    weight: 30
  - name: 프로젝트
    identifier: projects 
    weight: 40
  - name: 블로그  
    url: '/blog/'
    weight: 50
  - name: 여행   
    url: '/travel/'
    weight: 60
    
  - name: 포트폴리오 웹사이트 구축
    parent: projects
    url: '/post/portfolio/' 
    weight: 3
  - name: Oracle 데이터베이스 설계
    parent: projects
    url: '/post/database/'
    weight: 2
  - name: Java 나루토 팬 게임
    parent: projects
    url: '/post/naruto-game/'
    weight: 1