
# Appearance
appearance:
  mode: system
  color: green  

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: '전북대학교 IT정보공학과 최우성의 포트폴리오 사이트'  
    twitter: ''  
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: '여기에 구글 인증코드를 입력하세요'  
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: navbar-theme-switcher

# Site footer
footer:
  copyright:
    notice: '© {year} Choi Wooseong. This work is licensed under {license}'  
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: '2025년 10월 11일'  
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  font_awesome:
    enable: true
    block: navbar